### ISSUE TITLE
Bug when toggling costs in the console

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#1131]
**Describe the bug**
If I enable cost tracking in the console, then make a contract call, clarinet crashes.

**To Reproduce**
1. Run `clarinet console`
2. Define a public function:
```clar
(define-public (foo) (ok true))
```
3. Toggle costs on:
```
::toggle_costs
```
4. Call the function
```clarity
(contract-call? .contract-0 foo)
```
5. See the crash:
```
thread 'main' panicked at 'failed to initialize cost tracker: CostComputationFailed("Unchecked(NoSuchDataVariable(\"confirmed-proposal-count\"))")', components/clarity-repl/src/repl/interpreter.rs:461:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
I expect this to successfully call the function and return `(ok true)`.

**Environment (please complete the following information):**
 - OS (version): macOS (13.5)
 - Clarinet version: 1.7.1

**Comment by lgalabru** [comment]
hey @obycode, thanks for opening this issue. is this blocking you for your hackathon?

**Comment by obycode** [comment]
Nope, just noticed it will testing something out.

**Comment by tippenein** [comment]
while looking into #1156 I noticed a similar issue. It seems to be a cost-related error in general
```
>> (define-public (foo) (ok true))
→ .ST000000000000000000002AMW42H.contract-0 contract successfully stored. Use (contract-call? ...) for invoking the public functions:
>> ::get_costs .contract-0
thread 'main' panicked at 'failed to initialize cost tracker: CostComputationFailed("Unchecked(NoSuchDataVariable(\"confirmed-proposal-count\"))")', components/clarity-repl/src/repl/interpreter.rs:482:18
```

At a glance it seems to happen in the clarity-vm, rather than the actually interpreter call.

**Comment by hugocaillard** [comment]
Hey @tippenein 
I'll look into that, I'll follow up on discord, where you posted a message 👍

**Comment by hugocaillard** [comment]
Hey @tippenein 
Thanks for investigating, I think your comment above and message on Discord put me on the right track.

The `clarinet console` can be used in two ways:
- in a project, with a Clarinet.toml, where it would load the manifest and build a valid deployment.
- in standalone (no manifest and some default deployment)

The costs errors only happen in the standalone mode. I think that's because the boot contracts aren't loaded.

These is were we load the default settings:
```

**Comment by hugocaillard** [comment]
Hey @tippenein 
Thanks for investigating, I think your comment above and message on Discord put me on the right track.

The `clarinet console` can be used in two ways:
- in a project, with a Clarinet.toml, where it would load the manifest and build a valid deployment.
- in standalone (no manifest and some default deployment)

The costs errors only happen in the standalone mode. I think that's because the boot contracts aren't loaded.

These is were we load the default settings:
https://github.com/hirosystems/clarinet/blob/2afda6315d7ff9d09e5d4d822f34c5f202ca6dc9/components/clarinet-cli/src/frontend/cli.rs#L1059

I think we could override the Default method for SessionSettings to actually include the minimum required contracts, so at least the costs (maybe as we do here https://github.com/hirosystems/clarinet/blob/2afda6315d7ff9d09e5d4d822f34c5f202ca6dc9/components/clarity-repl/src/bin.rs#L39).

I don't know if `cost-voting.clar` is required, it worth a try.
We don't want to include _all_ boot contract because it can take a bit of time to parse and load them

**Comment by tippenein** [comment]
Tried the `include_boot_contracts` and unfortunately it didn't work. At least not yet, I'll keep digging into this though, it seems close, but I'm missing something still

**Comment by hugocaillard** [comment]
@tippenein You get the same error?
have you tried changing both
```
    pub include_boot_contracts: Vec<String>,
    pub include_costs: bool,
```

And which boot contract did you include?

**Comment by tippenein** [comment]
Yeah, I tried both and I'm including all the cost related just to see if it works

```
                        let settings = repl::SessionSettings {
                            include_costs: true,
                            include_boot_contracts: vec![
                                "costs".into(),
                                "cost-voting".into(),
                                "costs-2".into(),
                                "costs-3".into(),
                            ],
                            ..Default::default()
                        };
                        Terminal::new(settings)
  ```
  The weird part is this works if you go right to `define-public` but if you `::toggle_costs` then it seems to always throw the error

**Comment by tippenein** [comment]
Not sure why, but `disk_cache_enabled: true` fixes this. I'll try to shrink down the changes for this fix and then open a PR

**Comment by zuchka** [comment]
confirming that I can still reproduce this while in standalone mode. Starting to poke around at a possible fix:

```
❯ clarinet console
note: no manifest found, starting with default settings.
clarity-repl v2.10.0
Enter "::help" for usage hints.
Connected to a transient in-memory database.
>> (define-public (foo) (ok true))
→ .ST000000000000000000002AMW42H.contract-0 contract successfully stored. Use (contract-call? ...) for invoking the public functions:
>> ::get_costs .contract-0
error: Runtime Error: failed to initialize cost tracker: CostComputationFailed("Unchecked(NoSuchDataVariable(\"confirmed-proposal-count\"))")
```

**Comment by binadamu-isiyoonekana** [comment]
Hi,
  I tried with `clarity-repl 2.11.2` and all is working fine. Same for issue #1156. It worked like a charm.
  I wanted to contribute with a simple task first, so that to discover the sourc code. Any idea on an issue I could try to solve?
  Thanks.
  Ciao

**Comment by hugocaillard** [comment]
@binadamu-isiyoonekana It doesn't work if you are in not in clarinet project. That's the issue here

**Comment by hugocaillard** [comment]
Yes I think it's just that.
Previous attempts to fix it in the past didn't work, but alos, boot_contract handling in clarinet is a bit weird.
We'll try to have another look in Q1
