### ISSUE TITLE
running clarinet check throws this error

### ISSUE THREAD

**Issue by amrro** [hirosystems/clarinet#161]
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/types/project_config.rs:94:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by amrro** [comment]
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/types/project_config.rs:94:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:735:21
   4: clarinet::types::project_config::MainConfig::ordered_contracts
             at /Users/amrro/Developer/stx/clarinet/src/types/project_config.rs:94:30
   5: clarinet::poke::load_session
             at /Users/amrro/Developer/stx/clarinet/src/poke/mod.rs:59:27
   6: clarinet::frontend::cli::main
             at /Users/amrro/Developer/stx/clarinet/src/frontend/cli.rs:319:19
   7: clarinet::main
             at /Users/amrro/Developer/stx/clarinet/src/main.rs:30:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
```

**Comment by amrro** [comment]
I found out why, but the error wasn't helping enough. 
I accidentally made a trait the `depends_on` other trait.

**Comment by lgalabru** [comment]
Thanks for raising this issue.
Will close - the overall `depends_on` experience will be addressed with https://github.com/hirosystems/clarinet/issues/90.
