### ISSUE TITLE
Clarinet test throwing error on test execution

### ISSUE THREAD

**Issue by geek96** [hirosystems/clarinet#183]
I was trying to run the clarinet test, but always getting the empty receipts on contract call, I follow the calrinet examples but not sure what I did wrong.

Version: clarinet 0.18.0
OS: macOS Big Sur 11.6

## Test
```javascript
Clarinet.test({
    name: "Ensure that <>",
    async fn(chain: Chain, accounts: Map<string, Account>, contracts: Map<string, Contract>) {
        let deployer = accounts.get("deployer")!;
        let wallet_1 = accounts.get("wallet_1")!;
        let block = chain.mineBlock([
            Tx.contractCall("xyz-token", "transfer", [
                types.int(10000000000), 
                types.principal(deployer.address), 
                types.principal(wallet_1.address),
                types.none()
            ], deployer.address),
        ]);
        block.receipts[0].result.expectOk().expectBool(true);
    }
})
```
## Run
```bash
clarinet test
```
## Output
```javascript
TypeError: Cannot read property 'result' of undefined
    at Object.fn (file:///<>/tests/token_test.ts:49:27)
    at fn (https://deno.land/x/clarinet@v0.14.0/index.ts:237:23)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:21:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:58:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:85:15)
    at runTest (deno:runtime/js/40_testing.js:199:13)
    at Object.runTests (deno:runtime/js/40_testing.js:244:13)
    at async file:///<>/$deno$test.js:1:1
```

**Comment by obycode** [comment]
Hi @geek96. Could you post the associated contract here as well or link to a repo? It seems likely that the contract call is failing and that is why there are no receipts in the block. Possibly related to #91 - we need to improve the debugability of `mineBlock`.

**Comment by geek96** [comment]
@obycode  it's working in the clarinet console.

## Request
```
(contract-call? .xyz-token transfer u10000 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM 'ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5 none)
```

## Response:
```
Events emitted
{"type":"ft_transfer_event","ft_transfer_event":{"asset_identifier":"ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.xyz-token::xyz-token","sender":"ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM","recipient":"ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5","amount":"10000"}}
{"type":"contract_event","contract_event":{"contract_identifier":"ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.xyz-token","topic":"print","value":"none"}}
(ok true)
```

Here is the contract git repo
https://github.com/geek96/xyz-token-stacks.git

**Comment by geek96** [comment]
@obycode I figured out the issue, I was using types.int instead of types.uint. 

```
Clarinet.test({
    name: "Ensure that token can be transferred",
    async fn(chain: Chain, accounts: Map<string, Account>) {
        let deployer = accounts.get("deployer")!;
        let wallet_1 = accounts.get("wallet_1")!;
        let block = chain.mineBlock([
            Tx.contractCall("xyz-token", "transfer", [
                types.uint(1000),  // was using types.int(1000) here :)
                types.principal(deployer.address), 
                types.principal(wallet_1.address),
                types.none()
            ], deployer.address),
        ]);
        block.receipts[0].result.expectOk().expectBool(true);
    }
})
```

**Comment by obycode** [comment]
Great! Thanks for the update. I added a note to #91 and will close this one.
