### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', src/frontend/cli.rs:417:57

### ISSUE THREAD

**Issue by tyGavinZJU** [hirosystems/clarinet#22]
```
gavin@GavindeMacBook-Pro  ~/Desktop/DMTDAO  RUST_BACKTRACE=full clarinet contract new example.clar
Creating file contracts/example.clar.clar
Creating file tests/example.clar_test.ts
BEFORE: MainConfig { project: ProjectConfig { name: "DMTDAO" }, links: Some([]), contracts: Some({}) }
AFTER: MainConfig { project: ProjectConfig { name: "DMTDAO" }, links: Some([]), contracts: Some({"example.clar": ContractConfig { path: "contracts/example.clar.clar", depends_on: [] }}) }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', src/frontend/cli.rs:417:57
stack backtrace:
   0:        0x10415a4c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4b962ed89f71a03
   1:        0x104181cb0 - core::fmt::write::h94ae1e793baa7a00
   2:        0x10415234b - std::io::Write::write_fmt::h5c716758fdc3057f
   3:        0x10415c765 - std::panicking::default_hook::{{closure}}::hc6119c7d16548caf
   4:        0x10415c4a7 - std::panicking::default_hook::heae8b62897b351dc
   5:        0x10415cd05 - std::panicking::rust_panic_with_hook::hc36596b4257bea99
   6:        0x10415c89b - std::panicking::begin_panic_handler::{{closure}}::h49e5ddc3f21ca2fb
   7:        0x10415a938 - std::sys_common::backtrace::__rust_end_short_backtrace::h9bd32c9ad3fad18f
   8:        0x10415c85a - _rust_begin_unwind
   9:        0x1042133ff - core::panicking::panic_fmt::hcdc9362d34d55302
  10:        0x104213305 - core::result::unwrap_failed::h4cf11d46918a5fd4
  11:        0x101acda58 - clarinet::frontend::cli::execute_changes::h6f6e33bdfd5e2acf
  12:        0x101acb187 - clarinet::frontend::cli::main::hb70c98d8c2dd5113
  13:        0x101dd7aca - std::sys_common::backtrace::__rust_begin_short_backtrace::h87e5394eb6854131
  14:        0x101b78cfc - std::rt::lang_start::{{closure}}::h4831c2b9dd492b7a
  15:        0x10415d0a0 - std::rt::lang_start_internal::hd0c760d47f593c0a
  16:        0x101dedec9 - _main
```

**Comment by lgalabru** [comment]
Addressed with latest `0.9.3`
