### ISSUE TITLE
clarinet check crashes with 'called `Option::unwrap()` on a `None` 

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#334]
When running clarinet check on https://github.com/BTC-Rocks/btc-rocks/tree/main/backend-rescue I get the following error:

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /.cargo/registry/src/github.com-1ecc6299db9ec823/clarity-repl-0.26.0/src/analysis/ast_visitor.rs:135:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_list
   4: <clarity_repl::analysis::ast_dependency_detector::ASTDependencyDetector as clarity_repl::analysis::ast_visitor::ASTVisitor>::traverse_define_public
   5: clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_list
   6: clarity_repl::analysis::ast_dependency_detector::ASTDependencyDetector::detect_dependencies
   7: clarity_repl::repl::session::Session::interpret_initial_contracts
   8: clarity_repl::repl::session::Session::start
   9: clarinet::poke::load_session
  10: clarinet::frontend::cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by obycode** [comment]
Looks like the cause is the `let` expression on line 22. There should be another pair of parentheses:

```clarity
  (let ((details (unwrap! (map-get? rescues id) err-not-found)))
  ...)
```

The new dependency detector now runs before other checks and uses that AST visitor, so now the AST visitor needs to be hardened a bit to handle ASTs with errors in them. I will add this to the todo list so that it will provide a nicer error.

**Comment by friedger** [comment]
Thank you!
