### ISSUE TITLE
Improve message on "incorrect number of arguments" error

### ISSUE THREAD

**Issue by gregorycoppola** [hirosystems/clarinet#430]
## Problem

When there is an incorrect number of function arguments, `clarinet check` just panics instead of returning a nice error saying where the problem is:

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clarity-repl-0.28.0/src/analysis/ast_visitor.rs:149:75
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:84:5
   3: clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_list
   4: clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_let
   5: clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_list
   6: <clarity_repl::analysis::ast_dependency_detector::ASTDependencyDetector as clarity_repl::analysis::ast_visitor::ASTVisitor>::traverse_define_private
   7: clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_list
   8: clarity_repl::analysis::ast_dependency_detector::ASTDependencyDetector::detect_dependencies
   9: clarinet::deployment::generate_default_deployment
  10: clarinet::frontend::cli::load_deployments_and_artifacts_or_exit
  11: clarinet::frontend::cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

See the contract at https://github.com/hirosystems/stacks-hyperchains/blob/draft/no-mint-ft/core-contracts/contracts/hyperchains.clar

## Request
Put a nice message with the line numbers involved

**Comment by lgalabru** [comment]
Thanks for opening this issue @gregorycoppola!
I'll close this issue, as we're already tracking it here https://github.com/hirosystems/clarinet/issues/91.
