### ISSUE TITLE
expectUint() and expectInt() consume left to right, leading to assertions passing when they should not

### ISSUE THREAD

**Issue by MarvinJanssen** [hirosystems/clarinet#47]
```TS
"u100".expectUint(1); // pass
"u100".expectUint(10); // pass
"u100".expectUint(100); // pass
"u100".expectUint(1000); // fail
"100".expectInt(1); // pass
"100".expectInt(10); // pass
"100".expectInt(100); // pass
"100".expectInt(1000); // fail
```

**Comment by lgalabru** [comment]
Addressed with latest master (not published on deno.land yet).

**Comment by lgalabru** [comment]
To fix this issue in your project, you can update your import with:
`import { Clarinet, Tx, Chain, Account, types } from 'https://deno.land/x/clarinet@v0.13.0/index.ts';`

Feel free to close this issue once this is resolved on your end!

**Comment by MarvinJanssen** [comment]
Hmm. I get this with v0.13.0.

```
TypeError: Deno.core.opSync is not a function
    at fn (https://deno.land/x/clarinet@v0.13.0/index.ts:224:52)
    at asyncOpSanitizer (deno:deno_runtime-0.9.3/js/40_testing.js:38:15)
    at resourceSanitizer (deno:deno_runtime-0.9.3/js/40_testing.js:74:13)
    at Object.exitSanitizer [as fn] (deno:deno_runtime-0.9.3/js/40_testing.js:101:15)
    at TestRunner.[Symbol.asyncIterator] (deno:deno_runtime-0.9.3/js/40_testing.js:275:24)
    at AsyncGenerator.next (<anonymous>)
    at Object.runTests (deno:deno_runtime-0.9.3/js/40_testing.js:352:22)
    at async /clarity-experiments/$deno$test.ts:12:1
```

**Comment by lgalabru** [comment]
I think it indicates that you're not using a `clarity-cli` 0.13 with a 0.13 library.
I updated deno with 0.12, and a few interfaces changed and broke.

**Comment by MarvinJanssen** [comment]
That seemed to have fixed the issue above, however:

```
running 23 tests from clarity-experiments/tests/tiny-market_test.ts
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("u128 is not supported", line: 0, column: 0)', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/clarity-repl-0.13.1/src/clarity/events.rs:188:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
zsh: abort      clarinet test tests/tiny-market_test.ts
```

**Comment by lgalabru** [comment]
Addressed with latest
