### ISSUE TITLE
expectPrintEvent doesn't recognize string

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#540]
## Summary

I'm working on a [new repository for CityCoin contracts](https://github.com/citycoins/protocol/tree/feat/initial-config) and am trying to compare a set of print events to the expected results.

To do so I set the expected events in a constant and iterate over it, but the final value throws an error with `clarinet test`:

```
failures:

base-dao: succeeds when initializing the DAO with bootstrap proposal
Error: Unable to retrieve expected PrintEvent
    at Array.expectPrintEvent (https://deno.land/x/clarinet@v0.34.0/index.ts:790:9)
    at Object.fn (file:///home/whoabuddy/Dev/citycoins/protocol/tests/base-dao.test.ts:36:26)
    at fn (https://deno.land/x/clarinet@v0.34.0/index.ts:276:23)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:21:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:58:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:85:15)
    at runTest (deno:runtime/js/40_testing.js:199:13)
    at Object.runTests (deno:runtime/js/40_testing.js:244:13)
    at file:///home/whoabuddy/Dev/citycoins/protocol/$deno$test.js:1:27
```

## Print Event

The receipt for the block shows the correct print events when console logging:

```json
[
  {
    "result": "(ok true)",
    "events": [
      {
        "type": "contract_event",
        "contract_event": {
          "contract_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.base-dao",
          "topic": "print",
          "value": "{event: \"execute\", proposal: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccip012-bootstrap}"
        }
      },
      {
        "type": "contract_event",
        "contract_event": {
          "contract_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.base-dao",
          "topic": "print",
          "value": "{enabled: true, event: \"extension\", extension: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccd001-direct-execute}"
        }
      },
      {
        "type": "contract_event",
        "contract_event": {
          "contract_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.base-dao",
          "topic": "print",
          "value": "{enabled: true, event: \"extension\", extension: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccd002-treasury-mia}"
        }
      },
      {
        "type": "contract_event",
        "contract_event": {
          "contract_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.base-dao",
          "topic": "print",
          "value": "{enabled: true, event: \"extension\", extension: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccd002-treasury-nyc}"
        }
      },
      {
        "type": "contract_event",
        "contract_event": {
          "contract_identifier": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccip012-bootstrap",
          "topic": "print",
          "value": "\"CityCoins DAO has risen! Our mission is to empower people to take ownership in their city by transforming citizens into stakeholders with the ability to fund, build, and vote on meaningful upgrades to their communities.\""
        }
      }
    ]
  }
]
```

## Expected Events

I'm using a constant to iterate over the expected events:

```ts
const expectedPrintEvents = [
  '{event: "execute", proposal: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccip012-bootstrap}',
  '{enabled: true, event: "extension", extension: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccd001-direct-execute}',
  '{enabled: true, event: "extension", extension: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccd002-treasury-mia}',
  '{enabled: true, event: "extension", extension: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.ccd002-treasury-nyc}',
  '"CityCoins DAO has risen! Our mission is to empower people to take ownership in their city by transforming citizens into stakeholders with the ability to fund, build, and vote on meaningful upgrades to their communities."',
];
```

## Workaround

This is a bit funky, but if I compare the event from the receipt directly with the event from my expected array it succeeds:

```ts
const brokenReceiptEvent = receipts[0].events[4].contract_event.value;
const brokenPrintEvent = expectedPrintEvents[4];

for (const event of expectedPrintEvents) {
  if (event === brokenPrintEvent) {
    assertEquals(brokenReceiptEvent, event);
    continue;
  }
  receipts[0].events.expectPrintEvent(BASE_DAO, event);
}
```

[Code for Reference](https://github.com/citycoins/protocol/blob/feat/initial-config/tests/base-dao.test.ts)

**Comment by hugocaillard** [comment]
Hey @whoabuddy
The last event `expectedPrintEvents` is emitted by `.ccip012-bootstrap`, and not `.base-dao`. This is why the test fails.

But the clarinet lib doesn't return the right error and instead throws the confusing message `"Unable to retrieve expected PrintEvent"` as you've seen. So I'll definitely try to improve it.

Here's something that could works for you in the:

```ts
    const expectedPrintEvents = [
      `{event: "execute", proposal: ${ADDRESS}.ccip012-bootstrap}`,
      `{enabled: true, event: "extension", extension: ${ADDRESS}.ccd001-direct-execute}`,
      `{enabled: true, event: "extension", extension: ${ADDRESS}.ccd002-treasury-mia}`,
      `{enabled: true, event: "extension", extension: ${ADDRESS}.ccd002-treasury-nyc}`,
    ];

    for (const event of expectedPrintEvents) {
      receipts[0].events.expectPrintEvent(BASE_DAO, event);
    }

    receipts[0].events
      .slice(-1)
      .expectPrintEvent(
        PROPOSALS.CCIP_012,
        '"CityCoins DAO has risen! Our mission is to empower people to take ownership in their city by transforming citizens into stakeholders with the ability to fund, build, and vote on meaningful upgrades to their communities."'
      );
 ```

**Comment by whoabuddy** [comment]
Thank you for this! Something very simple and right in front of me haha

I will definitely try this out and appreciate the PR too, I'm still getting used to the standard test structure as we used something a bit different for CityCoins originally.

**Comment by hugocaillard** [comment]
You can close the issue if you thanks its solved 👌 

I'll work on improving the message as part of #573
