### ISSUE TITLE
Panic when adding boom-nfts as a requirements 

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#658]
When adding the following requirement, clarinet crashes

```
[[project.requirements]]
contract_id = "SP497E7RX3233ATBS2AB9G4WTHB63X5PBSP5VGAQ.boom-nfts"
```

The error is:
``` 
thread 'main' panicked at 'unable to retrieve contract', /home/runner/work/clarinet/clarinet/components/clarinet-deployments/src/lib.rs:468:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1880:5
   5: clarinet_deployments::generate_default_deployment::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: std::thread::local::LocalKey<T>::with
   8: tokio::park::thread::CachedParkThread::block_on
   9: tokio::runtime::handle::Handle::block_on
  10: hiro_system_kit::nestable_block_on
  11: clarinet::frontend::cli::load_deployment_and_artifacts_or_exit
  12: clarinet::frontend::cli::main
  ```
Using version clarinet-cli 1.0.5

Git repo: https://github.com/Rapha-btc/The-21-Bitcoin-days

**Comment by Rapha-btc** [comment]
Thxs for the help FM. I'll try cloning https://github.com/BTC-Rocks/btc-rocks.git now and run it, to see if I get the same error message.

**Comment by lgalabru** [comment]
Thanks @friedger @Rapha-btc for opening this issue.
This is being addressed in https://github.com/hirosystems/clarinet/pull/659 we should be able to slip this hot fix in today's release.

**Comment by Rapha-btc** [comment]
that's really great, thank you Ludo! Ps: Par ailleurs, tu es francais?

**Comment by Rapha-btc** [comment]
Thank you Ludo. :) 

Looking fwd to test what Friedger did [for Bitcoin days.](https://gamma.io/collections/seven-bitcoin-days)
