### ISSUE TITLE
Clarinet LSP not working with neovim

### ISSUE THREAD

**Issue by Shifta-Robel** [hirosystems/clarinet#986]
I am experiencing issues while trying to use the Clarinet LSP with neovim. My `lspconfig.lua` is set up like this 
```lua
local lspconfig = require("lspconfig")
lspconfig.clarity_lsp.setup {
        cmd = {"clarinet", "lsp"},
        filetypes = {"clar", "clarity"},
        root_dir = lspconfig.util.root_pattern(".git", "Clarinet.toml")
}
```
And here's the generated error message in my lsp.log
```log
[START][2023-05-03 19:36:08] LSP logging initiated
[ERROR][2023-05-03 19:36:08] .../vim/lsp/rpc.lua:734	"rpc"	"clarinet"	"stderr"	"thread '<unnamed>' panicked at 'failed to parse initialization options', components/clarity-lsp/src/common/backend.rs:386:18\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\nthread 'main' panicked at 'failed to get value from recv: RecvError', components/clarinet-cli/src/lsp/native_bridge.rs:109:47\n"
```

**Comment by hugocaillard** [comment]
Thanks for reporting @Shifta-Robel 

Do you think you could test [this branch](https://github.com/hirosystems/clarinet/pull/993)? You'll have to build it locally as explained [here](https://github.com/hirosystems/clarinet#build-clarinet).

I'll try it as well but need to setup another editor

**Comment by hugocaillard** [comment]
@Shifta-Robel 
I pushed an update to the branch.

A workaround would be to set the Initialize Options in your LSP config. This is what currently expected:
```
{ 
    completion: true,
    completion_smart_parenthesis_wrap: true,
    completion_include_native_placeholders: true,
    document_symbols: false,
    go_to_definition: true,
    hover: true,
    signature_help: true,
}
```

With the fix, I'll set default value for these options if not set.

The LSP has been tested with VSCode but not so much with other editors lately. So it might require some more fine tuning but we'll get there

**Comment by hugocaillard** [comment]
@Shifta-Robel With the local build or by setting option?
